// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    FHead: typeof import('./src/components/Layout/FHead.vue')['default']
    FixedMainHead: typeof import('./src/components/Layout/FixedMainHead.vue')['default']
    FLNav: typeof import('./src/components/Layout/FLNav.vue')['default']
    FMHead: typeof import('./src/components/Layout/FMHead.vue')['default']
    FMine: typeof import('./src/components/Layout/FMine.vue')['default']
    FNav: typeof import('./src/components/Layout/FNav.vue')['default']
    FSearch: typeof import('./src/components/Layout/FSearch.vue')['default']
    Headr: typeof import('./src/components/Layout/Headr.vue')['default']
    HeadR: typeof import('./src/components/HeadR.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Layout: typeof import('./src/components/Layout/Layout.vue')['default']
    LayoutHome: typeof import('./src/components/Layout/LayoutHome.vue')['default']
    LeftTiele: typeof import('./src/components/wheel/LeftTiele.vue')['default']
    LikeIcon: typeof import('./src/components/wheel/LikeIcon.vue')['default']
    Likes: typeof import('./src/components/Likes.vue')['default']
    Login: typeof import('./src/components/Login/Login.vue')['default']
    LoginPa: typeof import('./src/components/Login/LoginPa.vue')['default']
    LoginQr: typeof import('./src/components/Login/LoginQr.vue')['default']
    Lyric: typeof import('./src/components/Lyric.vue')['default']
    Mine: typeof import('./src/components/Layout/Mine.vue')['default']
    Nav: typeof import('./src/components/Layout/Nav.vue')['default']
    NewMusic: typeof import('./src/components/Layout/newMusic.vue')['default']
    PlaySong: typeof import('./src/components/PlaySong.vue')['default']
    RecommendSongSheet: typeof import('./src/components/Layout/RecommendSongSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Layout/Search.vue')['default']
    Signin: typeof import('./src/components/Layout/Signin.vue')['default']
    SongLi: typeof import('./src/components/wheel/SongLi.vue')['default']
    SongList: typeof import('./src/components/SongList.vue')['default']
    Tail: typeof import('./src/components/Tail.vue')['default']
    Topic: typeof import('./src/components/Layout/Topic.vue')['default']
    Use: typeof import('./src/components/use.vue')['default']
    UseName: typeof import('./src/components/useName.vue')['default']
    UseSongName: typeof import('./src/components/useSongName.vue')['default']
  }
}
